###
http://193.112.41.28:8090/money_api/accounts/

###
http://193.112.41.28:8090/money_api/accounts/7/

###
POST http://193.112.41.28:8090/money_api/accounts/5/adjust_balance/
Content-type: "application/json"

{
    "new_balance": -5326
}

###
http://localhost:8000/money_api/transactions/

###
http://localhost:8000/money_api/update_currency/
