# Generated by Django 2.2.6 on 2019-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_account', models.IntegerField(default=0)),
                ('in_account', models.IntegerField(default=0)),
                ('out_amt', models.FloatField(default=0)),
                ('in_amt', models.FloatField(default=0)),
                ('trans_rate', models.FloatField(default=0)),
                ('date_time', models.DateTimeField()),
                ('catalog', models.IntegerField(default=0)),
                ('project', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
