# Generated by Django 2.2.6 on 2019-10-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField(default=0)),
                ('logo', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Cash'), (3, 'Debit'), (5, 'Credit')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='money.Catalog'),
        ),
    ]
