# Generated by Django 2.2.6 on 2019-10-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20191010_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remark',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
