# Generated by Django 2.2.6 on 2019-10-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_project_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, '支出'), (3, '收入'), (5, '转账'), (7, '调整')], default=0),
        ),
    ]
