# Generated by Django 2.2.6 on 2019-10-11 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_auto_20191010_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money.Account')),
                ('credit_limit', models.FloatField(default=0)),
                ('billing_day', models.IntegerField(default=0)),
                ('billing_cycle', models.IntegerField(default=0)),
                ('include_today', models.BooleanField(default=False)),
            ],
            bases=('money.account',),
        ),
    ]
