# Generated by Django 2.2.6 on 2019-10-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0009_creditaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country_zh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, '现金'), (3, '借记卡'), (5, '信用卡')], default=0),
        ),
    ]
