# Generated by Django 2.2.6 on 2019-10-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_auto_20191011_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=328, on_delete=django.db.models.deletion.DO_NOTHING, to='money.Currency'),
            preserve_default=False,
        ),
    ]
