# Generated by Django 2.1.3 on 2018-11-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Summary', models.CharField(max_length=2048)),
                ('Link', models.CharField(max_length=200)),
                ('PublishDate', models.DateTimeField(verbose_name='date published')),
                ('Status', models.IntegerField(choices=[(0, 'None'), (1, 'WillDownload'), (2, 'Downloading'), (3, 'Downloaded'), (4, 'Error'), (5, 'Deleted')], default=0)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Remark', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
