# Generated by Django 2.1.3 on 2018-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='MirrorLink',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='Link',
            field=models.CharField(max_length=512),
        ),
    ]
