# Generated by Django 2.1.1 on 2018-11-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='DownloadResult',
            new_name='Remark',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='IsDownloaded',
        ),
        migrations.AddField(
            model_name='podcast',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
