# Generated by Django 2.1.1 on 2018-11-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20181102_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='Remark',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='Status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'WillDownload'), (2, 'Downloading'), (3, 'Downloaded'), (4, 'Error'), (5, 'Deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='Summary',
            field=models.CharField(max_length=2048),
        ),
    ]
