# Generated by Django 2.0.4 on 2018-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('txt', models.CharField(max_length=65536)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
