# Generated by Django 2.0.4 on 2018-04-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='txt',
            new_name='text',
        ),
    ]
