# Generated by Django 2.0.4 on 2018-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20180427_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
