# Generated by Django 2.0.4 on 2018-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20180427_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '主题'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
