# Generated by Django 2.2.6 on 2019-10-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('weather', models.CharField(blank=True, max_length=512, null=True)),
                ('picture', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
