# Generated by Django 2.0.5 on 2018-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=200)),
                ('subs_link', models.CharField(max_length=400)),
                ('is_acive', models.CharField(choices=[(1, '启用'), (2, '暂停')], default=1, max_length=2)),
                ('count', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
