# Generated by Django 2.0.5 on 2018-07-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_acive',
            new_name='is_active',
        ),
    ]
